# Generated by Django 4.2 on 2025-03-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='distance',
            new_name='weight',
        ),
    ]
